version: '3'
services:
  web:
    build: '.'
    ports:
      - "3001:3000"
    env_file:
      - .env
      - .env.local
    restart:
      unless-stopped
    depends_on:
      - db
    
  db:
    image: postgres
    restart: always
    # env_file:
    #   - .env
    #   - .env.local
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: